name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  desktop:
    name: Desktop JDK 17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Generate Gradle wrapper
        run: gradle wrapper
      - name: Build and test
        run: ./gradlew testDebugUnitTest

  android:
    name: Android API ${{ matrix.api-level }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [34, 33, 32, 30]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: "platforms;android-${{ matrix.api-level }} build-tools;33.0.0"
      - name: Generate Gradle wrapper
        run: gradle wrapper
      - name: Build and test
        run: ./gradlew testDebugUnitTest
